$tag = git describe --always --tags "--abbrev=0" --exclude latest 2>$null
$revision = git describe --always --tags --exclude latest 2>$null

# Validate if the tag is a valid AssemblyVersion (e.g. 3.6.1)
$isValidTag = $false
if (![string]::IsNullOrWhiteSpace($tag)) {
    try {
        [version]$tag | Out-Null
        $isValidTag = $true
    } catch {}
}

if (!$isValidTag) {
    $tag = "3.6.1"
}
if ([string]::IsNullOrWhiteSpace($revision)) {
    $revision = "3.6.1-local"
}

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$tag")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8
